import { Inject, Injectable, Logger } from '@nestjs/common';
import { PgTransactionManager } from '../../../common/database/pg-transaction-manager';
import { ForeignKeyViolationError, UniqueConstraintViolationError } from '../../../common/database/errors/database-infrastructure.error';
import { OBJECT_STORAGE } from '../../../common/storage/storage.tokens';
import type { ObjectStorage } from '../../../common/storage/object-storage.interface';
import { PASSWORD_HASHER } from '../../../common/security/security.tokens';
import type { PasswordHasher } from '../../../common/security/password-hasher.interface';
import { studentException, studentUniqueMessage } from '../errors/student.errors';
import type { Student } from '../domain/student.entity';
import type { StudentWriteInput } from '../domain/student.contracts';
import { StudentRepository } from '../infrastructure/student.repository';

const allowedImages=new Set(['image/jpeg','image/jpg','image/png']);

@Injectable()
export class StudentCommandService {
  private readonly logger=new Logger(StudentCommandService.name);
  constructor(private readonly repository:StudentRepository,private readonly transactions:PgTransactionManager,@Inject(PASSWORD_HASHER) private readonly passwords:PasswordHasher,@Inject(OBJECT_STORAGE) private readonly storage:ObjectStorage){}
  activeHobbyMask(){return this.repository.activeHobbyMask();}
  async create(input:StudentWriteInput,file?:Express.Multer.File):Promise<Student>{let attachment:string|null=null;try{attachment=(await this.upload(file,input.code??'student'))??null;const password=await this.passwords.hash(input.password!);return await this.repository.create({...input,password,attachment});}catch(error){await this.removeNew(attachment);throw this.mapCreate(error);}}
  async update(id:number,input:StudentWriteInput,file?:Express.Multer.File):Promise<Student>{const oldAttachment=file?await this.repository.attachmentOfActive(id):undefined;if(file&&oldAttachment===undefined)throw studentException.updateNotFound();let attachment:string|undefined;let updated=false;try{attachment=await this.upload(file,`id${id}`);const result=await this.transactions.run(async(client)=>{const values:StudentWriteInput={...input};if(values.password==='')delete values.password;else if(values.password!==undefined)values.password=await this.passwords.hash(values.password);if(attachment!==undefined)values.attachment=attachment;return this.repository.updateActive(id,values,client);});if(!result)throw studentException.updateNotFound();updated=true;if(attachment&&oldAttachment&&oldAttachment!==attachment)await this.removeOld(oldAttachment);return result;}catch(error){if(!updated)await this.removeNew(attachment);throw this.mapUpdate(error);}}
  async destroy(id:number):Promise<{id:number}>{const removed=await this.transactions.run((client)=>this.repository.softDeleteActive(id,client));if(!removed)throw studentException.destroyNotFound();return{id};}
  async destroyMany(ids:unknown[]):Promise<{deleted:unknown[];notFound:unknown[]}>{return this.transactions.run(async(client)=>{const deleted:unknown[]=[];const notFound:unknown[]=[];for(const raw of ids){const id=typeof raw==='number'?raw:Number(raw);if(!Number.isFinite(id)||!(await this.repository.softDeleteActive(id,client)))notFound.push(raw);else deleted.push(raw);}if(!deleted.length&&notFound.length)throw studentException.destroyManyNotFound(notFound);return{deleted,notFound};});}
  async restore(ids:number[]):Promise<{restored:number[];notFound:number[];conflicts:number[]}>{return this.transactions.run(async(client)=>{const restored:number[]=[];const notFound:number[]=[];const conflicts:number[]=[];for(const id of new Set(ids)){const result=await this.repository.restoreDeleted(id,client);if(result==='restored')restored.push(id);else if(result==='conflict')conflicts.push(id);else notFound.push(id);}return{restored,notFound,conflicts};});}
  async permanentlyDelete(ids:number[]):Promise<{deleted:number[];notFound:number[]}>{const result=await this.transactions.run(async(client)=>{const deleted:number[]=[];const notFound:number[]=[];const candidates:string[]=[];for(const id of new Set(ids)){const removed=await this.repository.permanentlyDelete(id,client);if(!removed){notFound.push(id);continue;}deleted.push(id);if(removed.attachment)candidates.push(removed.attachment);}const attachments:string[]=[];for(const attachment of new Set(candidates)){if(await this.repository.countAttachmentReferences(attachment,client)===0)attachments.push(attachment);}return{deleted,notFound,attachments};});for(const attachment of result.attachments)await this.removeOld(attachment);return{deleted:result.deleted,notFound:result.notFound};}
  private async upload(file:Express.Multer.File|undefined,keyPart:string):Promise<string|undefined>{if(!file)return undefined;if(!allowedImages.has(file.mimetype)||file.size>5*1024*1024)throw studentException.createValidation('\u1ea2nh ph\u1ea3i l\u00e0 jpg/jpeg/png, t\u1ed1i \u0111a 5MB');const name=file.originalname.replace(/[^A-Za-z0-9._-]/g,'_');const key=`students/${keyPart.replace(/[^A-Za-z0-9._-]/g,'_')}-${Date.now()}-${name}`;await this.storage.upload({key,body:file.buffer,contentType:file.mimetype});return this.storage.getPublicUrl(key);}
  private async removeNew(url:string|null|undefined):Promise<void>{if(!url)return;try{await this.storage.delete(url);}catch{this.logger.warn('Could not compensate newly uploaded student attachment.');}}
  private async removeOld(url:string):Promise<void>{try{await this.storage.delete(url);}catch{this.logger.warn('Could not remove superseded student attachment after database success.');}}
  private mapCreate(error:unknown):unknown{if(error instanceof UniqueConstraintViolationError)throw studentException.createDuplicate(studentUniqueMessage(error.constraint),error);if(error instanceof ForeignKeyViolationError)throw studentException.createClassNotFound(error);throw error;}
  private mapUpdate(error:unknown):unknown{if(error instanceof UniqueConstraintViolationError)throw studentException.updateDuplicate(studentUniqueMessage(error.constraint),error);if(error instanceof ForeignKeyViolationError)throw studentException.updateClassNotFound(error);throw error;}
}
