import { StudentCommandService } from './student-command.service';

const transaction={run:async<T>(work:(client:never)=>Promise<T>)=>work({} as never)};
const hasher={hash:jest.fn(async(value:string)=>`hash:${value}`),compare:jest.fn()};
const input={code:'CT-1',fullname:'Contract Student',email:'ct@example.test',username:'ct',password:'Valid1!x',hobbies:0};

describe('StudentCommandService',()=>{
  it('hashes create passwords and never returns a hash',async()=>{const repository={create:jest.fn().mockResolvedValue({id:'1',code:'CT-1'})};const service=new StudentCommandService(repository as never,transaction as never,hasher);await expect(service.create(input)).resolves.toEqual({id:'1',code:'CT-1'});expect(repository.create).toHaveBeenCalledWith(expect.objectContaining({password:'hash:Valid1!x',attachment:null}));});
  it('keeps an existing password when update receives an empty one',async()=>{const repository={updateActive:jest.fn().mockResolvedValue({id:'1'}),attachmentOfActive:jest.fn()};const service=new StudentCommandService(repository as never,transaction as never,hasher);await service.update(1,{password:''});expect(repository.updateActive).toHaveBeenCalledWith(1,{},expect.anything());});
  it('compensates a newly uploaded image when create database insert fails',async()=>{const storage={upload:jest.fn(),getPublicUrl:jest.fn().mockResolvedValue('stored://new'),delete:jest.fn()};const repository={create:jest.fn().mockRejectedValue(new Error('db failed'))};const service=new StudentCommandService(repository as never,transaction as never,hasher,storage);const file={mimetype:'image/png',size:4,buffer:Buffer.from('x'),originalname:'a.png'} as Express.Multer.File;await expect(service.create(input,file)).rejects.toThrow('db failed');expect(storage.delete).toHaveBeenCalledWith('stored://new');});
  it('removes a new upload on update failure but preserves the old image',async()=>{const storage={upload:jest.fn(),getPublicUrl:jest.fn().mockResolvedValue('stored://new'),delete:jest.fn()};const repository={attachmentOfActive:jest.fn().mockResolvedValue('stored://old'),updateActive:jest.fn().mockRejectedValue(new Error('db failed'))};const service=new StudentCommandService(repository as never,transaction as never,hasher,storage);const file={mimetype:'image/png',size:4,buffer:Buffer.from('x'),originalname:'a.png'} as Express.Multer.File;await expect(service.update(2,{fullname:'New'},file)).rejects.toThrow('db failed');expect(storage.delete).toHaveBeenCalledWith('stored://new');expect(storage.delete).not.toHaveBeenCalledWith('stored://old');});
  it('removes an old image only after an update succeeds and tolerates cleanup failure',async()=>{const storage={upload:jest.fn(),getPublicUrl:jest.fn().mockResolvedValue('stored://new'),delete:jest.fn().mockRejectedValue(new Error('storage failed'))};const repository={attachmentOfActive:jest.fn().mockResolvedValue('stored://old'),updateActive:jest.fn().mockResolvedValue({id:'2',attachment:'stored://new'})};const service=new StudentCommandService(repository as never,transaction as never,hasher,storage);const file={mimetype:'image/png',size:4,buffer:Buffer.from('x'),originalname:'a.png'} as Express.Multer.File;await expect(service.update(2,{fullname:'New'},file)).resolves.toMatchObject({id:'2'});expect(storage.delete).toHaveBeenCalledWith('stored://old');});
  it('does not remove a shared attachment after permanent delete',async()=>{const storage={delete:jest.fn()};const repository={permanentlyDelete:jest.fn().mockResolvedValue({attachment:'shared://a'}),countAttachmentReferences:jest.fn().mockResolvedValue(1)};const service=new StudentCommandService(repository as never,transaction as never,hasher,storage);await expect(service.permanentlyDelete([7,7])).resolves.toEqual({deleted:[7],notFound:[]});expect(storage.delete).not.toHaveBeenCalled();});
});
