import { ApiResponseFactory } from '../../../common/http/api-response.factory';
import { LEGACY_FALLBACK_CODE } from '../../../common/http/legacy-fallback.decorator';
import type { ClassCommandService } from '../application/class-command.service';
import type { ClassQueryService } from '../application/class-query.service';
import { ClassRequestParser } from './class-request.parser';
import { ClassController } from './class.controller';
describe('ClassController', () => {
  it('orchestrates exact legacy envelopes and fixed fallback metadata', async () => { const query = { getAll: jest.fn().mockResolvedValue([]), getPage: jest.fn().mockResolvedValue({ page_info: {}, records: [] }), getDetail: jest.fn().mockResolvedValue({ id: '1' }) }; const command = { create: jest.fn().mockResolvedValue({ id: '1' }), update: jest.fn().mockResolvedValue({ id: '1' }), delete: jest.fn().mockResolvedValue({ id: '1' }), deleteMany: jest.fn().mockResolvedValue({ deletedIds: [], blockedIds: [] }) }; const controller = new ClassController(query as unknown as ClassQueryService, command as unknown as ClassCommandService, new ClassRequestParser(), new ApiResponseFactory()); await expect(controller.getAll()).resolves.toEqual({ code: '200', status: 200, message: 'Lấy danh sách lớp thành công', data: [] }); await expect(controller.create({ code: ' C1 ', name: ' A ' })).resolves.toEqual({ code: '200', status: 200, message: 'Tạo lớp thành công', data: { id: '1' } }); await expect(controller.update('1x', { code: 'ignored', description: 'd' })).resolves.toEqual({ code: '200', status: 200, message: 'Cập nhật lớp thành công', data: { id: '1' } }); expect(command.update).toHaveBeenCalledWith(1, { name: undefined, description: 'd' }); expect(Reflect.getMetadata(LEGACY_FALLBACK_CODE, ClassController.prototype.getAll)).toBe('B600'); expect(Reflect.getMetadata(LEGACY_FALLBACK_CODE, ClassController.prototype.getPage)).toBe('C600'); expect(Reflect.getMetadata(LEGACY_FALLBACK_CODE, ClassController.prototype.deleteMany)).toBe('I600'); });
});
