import { Inject, Injectable } from '@nestjs/common';
import type { Pool, PoolClient } from 'pg';
import { FileCodecRegistry } from '../../../common/files/file-codec.registry';
import type { FileFormat } from '../../../common/files/file-format.type';
import { PG_POOL } from '../../../common/database/database.tokens';
import { PgTransactionManager } from '../../../common/database/pg-transaction-manager';
import { PASSWORD_HASHER } from '../../../common/security/security.tokens';
import type { PasswordHasher } from '../../../common/security/password-hasher.interface';
import { LegacyApiException } from '../../../common/http/legacy-api.exception';
import type { StudentImportExportPort, StudentPersistenceRecord } from '../domain/student-persistence.port';

const columns = ['code','fullname','dob','gender','class','email','username','password','homecity','address','hobbies','description','hair_color','facebook'] as const;
const formats = ['csv','xlsx','json','xml'] as const;
const contentTypes: Record<FileFormat, string> = { csv:'text/csv', xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', json:'application/json', xml:'application/xml' };
const email = /^[0-9a-zA-Z.\-_]+@[0-9a-zA-Z.\-_]+$/;
const password = /^(?=.*[0-9])(?=.*[A-Z])(?=.*[a-z])(?=.*[^A-Za-z0-9\s]).{8,}$/;
type Values = { code:string; fullname:string; dob:string|null|undefined; gender:boolean|null|undefined; class:string; email:string; username:string; password:string; homecity:string; address:string; hobbies:string[]; description:string; hair_color:string; facebook:string };
type Draft = { draftKey:string; rowNumber:number; values:Values };

@Injectable()
export class StudentPostgresImportExportAdapter implements StudentImportExportPort {
  constructor(@Inject(PG_POOL) private readonly pool:Pool, private readonly transactions:PgTransactionManager, private readonly codecs:FileCodecRegistry, @Inject(PASSWORD_HASHER) private readonly passwords:PasswordHasher) {}

  async template(type: unknown) { return this.file([this.templateRow()], this.format(type), 'student-import-template'); }
  async exportOne(id:number,type:unknown) { const record=(await this.pool.query(`SELECT "id","code","fullname","dob","sex","class_id","email","username","homecity","address","hobbies","description","hair_color","facebook" FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NULL`,[id])).rows[0]; if(!record) throw this.error(404,'K604','Không tìm thấy sinh viên'); return this.exportRows([record],this.format(type),`student-${id}`); }
  async exportMany(ids:unknown[],type:unknown) { const records=(await this.pool.query(`SELECT "id","code","fullname","dob","sex","class_id","email","username","homecity","address","hobbies","description","hair_color","facebook" FROM "tra_student" WHERE "id"=ANY($1::int[]) AND "deleted_at" IS NULL ORDER BY "id" ASC`,[ids])).rows; return this.exportRows(records,this.format(type),'students-export'); }
  async preview(buffer:Buffer,filename:string) { const format=filename.split('.').pop()?.toLowerCase() as FileFormat; let rows:Record<string,unknown>[]; try { rows=await this.codecs.get(format).parse(buffer); } catch (error) { if(error instanceof Error&&error.message.startsWith('unsupported file format')) throw this.error(400,'J601','Định dạng file không được hỗ trợ (chỉ csv/xlsx/json/xml)'); throw this.error(400,'J604','Cannot parse import file'); } if(!rows.length) throw this.error(400,'J604','Import file has no rows'); return this.validate(rows.map((values,index)=>({draftKey:`import-${index+1}`,rowNumber:index+2,values}))); }
  async validate(raw:unknown, executor:Pool|PoolClient=this.pool) {
    const input=Array.isArray(raw)?raw:[]; const lookups=await this.lookups(executor); const classByCode=new Map(lookups.classes.map((item)=>[this.key(item.code),item])); const hobbyByName=new Map(lookups.hobbies.map((item)=>[this.key(item.name),item]));
    const normalized=input.map((item)=>this.values((item as {values?:Record<string,unknown>})?.values)); const valuesFor=(field:keyof Values)=>[...new Set(normalized.map((value)=>value[field]).filter((value):value is string=>typeof value==='string'&&Boolean(value)))];
    normalized.forEach((value,index)=>Object.assign(value,this.canonicalValues((input[index] as {values?:Record<string,unknown>})?.values)));
    const existing=(await executor.query(`SELECT "id","code","fullname","dob","sex","class_id","email","username","homecity","address","hobbies","description","hair_color","facebook" FROM "tra_student" WHERE ("code"=ANY($1::text[]) OR "email"=ANY($2::text[]) OR "username"=ANY($3::text[])) AND "deleted_at" IS NULL`,[valuesFor('code'),valuesFor('email'),valuesFor('username')])).rows;
    const existingByCode=new Map(existing.map((item)=>[item.code,item])); const counts={code:new Map<string,number>(),email:new Map<string,number>(),username:new Map<string,number>()}; normalized.forEach((value)=>{(['code','email','username'] as const).forEach((field)=>{if(value[field])counts[field].set(value[field],(counts[field].get(value[field])??0)+1);});});
    const rows=input.map((rawItem,index)=>{const item=rawItem as Partial<Draft>;const values=normalized[index];const errors:Record<string,string>={};const current=existingByCode.get(values.code); if(!values.code)errors.code='Mã sinh viên là bắt buộc';else if(values.code.length>50)errors.code='Mã sinh viên quá 50 ký tự';else if((counts.code.get(values.code)??0)>1)errors.code='Mã sinh viên bị trùng trong file'; if(!values.fullname)errors.fullname='Họ tên là bắt buộc';else if(values.fullname.length>30)errors.fullname='Họ tên quá 30 ký tự';if(!values.email||!email.test(values.email))errors.email='Email không hợp lệ';else if((counts.email.get(values.email)??0)>1)errors.email='Email bị trùng trong file';if(!values.username)errors.username='Username là bắt buộc';else if(values.username.length>50)errors.username='Username quá 50 ký tự';else if((counts.username.get(values.username)??0)>1)errors.username='Username bị trùng trong file';if(values.gender===undefined)errors.gender='Giới tính phải là Nam/Nữ hoặc True/False/1/0';if(values.dob===undefined)errors.dob='Ngày sinh phải theo DD/MM/YYYY'; for(const other of existing){if(other.code!==values.code&&other.email===values.email)errors.email=`Email đã thuộc về sinh viên ${other.code}`;if(other.code!==values.code&&other.username===values.username)errors.username=`Username đã thuộc về sinh viên ${other.code}`;}if(!current&&!values.password)errors.password='Password bắt buộc khi tạo mới';if(values.password&&(/^\$2[aby]\$/.test(values.password)||!password.test(values.password)))errors.password='Password import không hợp lệ';if(values.class&&!classByCode.has(this.key(values.class)))errors.class='Lớp không tồn tại';if(values.homecity.length>100)errors.homecity='homecity exceeds 100 characters';if(values.address.length>100)errors.address='address exceeds 100 characters';if(values.hair_color.length>7)errors.hair_color='hair_color exceeds 7 characters';if(values.email.length>256)errors.email='email exceeds 256 characters';if(values.facebook&&(values.facebook.length>256||!/^https?:\/\/[0-9a-zA-Z.\-_]+$/.test(values.facebook)))errors.facebook='facebook must be a valid http/https URL';const missingHobbies=values.hobbies.filter((name)=>!hobbyByName.has(this.key(name)));if(missingHobbies.length)errors.hobbies=`Hobby chưa tồn tại: ${missingHobbies.join('; ')}`;return{draftKey:typeof item.draftKey==='string'?item.draftKey:`import-${index+1}`,rowNumber:Number(item.rowNumber)||index+2,values,mode:current?'update':'create',errors,fieldErrors:errors,missingHobbies,status:Object.keys(errors).length?'invalid':'valid'};}); return{rows,lookups};
  }
  async commit(raw:unknown) { return this.transactions.run(async(client)=>{const preview=await this.validate(raw,client);const invalid=preview.rows.filter((row)=>row.status!=='valid');if(invalid.length)throw this.error(400,'J604','Import drafts are invalid',invalid);const codes=preview.rows.map((row)=>row.values.code);const locked=(await client.query('SELECT "id","code","password" FROM "tra_student" WHERE "code"=ANY($1::text[]) AND "deleted_at" IS NULL FOR UPDATE',[codes])).rows;const current=new Map(locked.map((row)=>[row.code,row]));const classes=new Map(preview.lookups.classes.map((row)=>[this.key(row.code),row]));const hobbies=new Map(preview.lookups.hobbies.map((row)=>[this.key(row.name),row]));const created:StudentPersistenceRecord[]=[];const updated:StudentPersistenceRecord[]=[];for(const row of preview.rows){const v=row.values;const classId=v.class?classes.get(this.key(v.class)).id:null;const mask=v.hobbies.reduce((value,name)=>value|Number(hobbies.get(this.key(name)).bit_value),0);const old=current.get(v.code);if(old){const values:unknown[]=[v.fullname,v.dob,v.gender,classId,v.email,v.username,v.homecity||null,v.address||null,mask,v.description||null,v.hair_color||null,v.facebook||null];let sets=['"fullname"=$1','"dob"=$2','"sex"=$3','"class_id"=$4','"email"=$5','"username"=$6','"homecity"=$7','"address"=$8','"hobbies"=$9','"description"=$10','"hair_color"=$11','"facebook"=$12','"updated_at"=NOW()'];if(v.password){values.push(await this.passwords.hash(v.password));sets.push(`"password"=$${values.length}`);}values.push(old.id);const result=await client.query(`UPDATE "tra_student" SET ${sets.join(',')} WHERE "id"=$${values.length} RETURNING "id","code"`,values);updated.push({draftKey:row.draftKey,rowNumber:row.rowNumber,record:result.rows[0]});}else{const result=await client.query(`INSERT INTO "tra_student" ("code","fullname","dob","sex","class_id","email","username","password","homecity","address","hobbies","description","hair_color","facebook","created_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,NOW(),NOW()) RETURNING "id","code"`,[v.code,v.fullname,v.dob,v.gender,classId,v.email,v.username,await this.passwords.hash(v.password),v.homecity||null,v.address||null,mask,v.description||null,v.hair_color||null,v.facebook||null]);created.push({draftKey:row.draftKey,rowNumber:row.rowNumber,record:result.rows[0]});}}return{created,updated};}); }
  private async exportRows(records:Record<string,unknown>[],format:FileFormat,name:string){const lookups=await this.lookups(this.pool);const classes=new Map(lookups.classes.map((row)=>[Number(row.id),String(row.code)]));return this.file(records.map((row)=>({code:row.code||'',fullname:row.fullname||'',dob:this.date(row.dob),gender:row.sex===true?'Nam':row.sex===false?'Nữ':'',class:classes.get(Number(row.class_id))||'',email:row.email||'',username:row.username||'',password:'',homecity:row.homecity||'',address:row.address||'',hobbies:lookups.hobbies.filter((hobby)=>Number(row.hobbies||0)&Number(hobby.bit_value)).map((hobby)=>hobby.name).join('; '),description:row.description||'',hair_color:row.hair_color||'',facebook:row.facebook||''})),format,name);}
  private async file(rows:Record<string,unknown>[],format:FileFormat,name:string){const normalized=rows.map((row)=>row.gender&&row.gender!=='Nam'?{...row,gender:'N\u1eef'}:row);return{buffer:await this.codecs.get(format).encode(normalized.map((row)=>Object.fromEntries(columns.map((column)=>[column,row[column]??''])))),contentType:contentTypes[format],filename:`${name}.${format}`};}
  private async lookups(executor:Pool|PoolClient){const [classes,hobbies]=await Promise.all([executor.query('SELECT "id","code" FROM "tra_class" ORDER BY "id" ASC'),executor.query('SELECT "id","name","bit_value" FROM "tra_hobby" WHERE "is_active"=true ORDER BY "bit_value" ASC')]);return{classes:classes.rows,hobbies:hobbies.rows};}
  private values(raw:Record<string,unknown>|undefined):Values{const text=(value:unknown)=>typeof value==='string'?value.trim():value==null?'':String(value).trim();const gender=text(raw?.gender??raw?.sex).toLocaleLowerCase('vi');const date=text(raw?.dob);const parsedDate=!date?null:/^(\d{2})\/(\d{2})\/(\d{4})$/.test(date)?this.iso(date):undefined;const hobbies=[...new Map(text(raw?.hobbies).split(';').map((item)=>item.trim()).filter(Boolean).map((item)=>[this.key(item),item])).values()];return{code:text(raw?.code),fullname:text(raw?.fullname),dob:parsedDate,gender:!gender?null:['nam','true','1'].includes(gender)?true:['nữ','nu','false','0'].includes(gender)?false:undefined,class:text(raw?.class??raw?.class_code??raw?.class_id),email:text(raw?.email).toLowerCase(),username:text(raw?.username),password:text(raw?.password),homecity:text(raw?.homecity),address:text(raw?.address),hobbies,description:text(raw?.description),hair_color:text(raw?.hair_color),facebook:text(raw?.facebook)};}
  private templateRow(){return{code:'SV001',fullname:'Nguyễn Văn An',dob:'15/01/2004',gender:'Nam',class:'',email:'sv001@example.com',username:'sv001',password:'Aa1!abcd',homecity:'Hà Nội',address:'',hobbies:'',description:'',hair_color:'#000000',facebook:''};}
  private format(value:unknown):FileFormat{const format=String(value??'xlsx').toLowerCase();if(!(formats as readonly string[]).includes(format))throw this.error(400,'K601','Định dạng export không hợp lệ (chỉ csv/xlsx/json/xml)');return format as FileFormat;}
  async commitSafe(raw:unknown){try{return await this.commit(raw);}catch(error){if(typeof error==='object'&&error!==null&&(error as {code?:string}).code==='23505')throw this.error(409,'J604','Duplicate student data');throw error;}}
  private canonicalValues(raw:Record<string,unknown>|undefined):Values{const text=(value:unknown)=>typeof value==='string'?value.trim():value==null?'':String(value).trim();const gender=text(raw?.gender??raw?.sex).toLocaleLowerCase('vi');const dob=text(raw?.dob);const parsedDate=!dob?null:/^(\d{2})\/(\d{2})\/(\d{4})$/.test(dob)?this.iso(dob):/^\d{4}-\d{2}-\d{2}$/.test(dob)?dob:undefined;const hobbies=[...new Map(text(raw?.hobbies).split(';').map((item)=>item.trim()).filter(Boolean).map((item)=>[this.key(item),item])).values()];return{code:text(raw?.code),fullname:text(raw?.fullname),dob:parsedDate,gender:!gender?null:['nam','true','1'].includes(gender)?true:['n\u1eef','nu','false','0'].includes(gender)?false:undefined,class:text(raw?.class??raw?.class_code??raw?.class_id),email:text(raw?.email).toLowerCase(),username:text(raw?.username),password:text(raw?.password),homecity:text(raw?.homecity),address:text(raw?.address),hobbies,description:text(raw?.description),hair_color:text(raw?.hair_color),facebook:text(raw?.facebook)};}
  private key(value:unknown){return String(value??'').trim().toLocaleLowerCase('vi');} private iso(value:string){const [,day,month,year]=value.match(/^(\d{2})\/(\d{2})\/(\d{4})$/)!;const date=new Date(`${year}-${month}-${day}T00:00:00Z`);return date.getUTCFullYear()===Number(year)&&date.getUTCMonth()+1===Number(month)&&date.getUTCDate()===Number(day)?`${year}-${month}-${day}`:undefined;} private date(value:unknown){if(!value)return'';const d=new Date(String(value));return Number.isNaN(d.getTime())?'':`${String(d.getUTCDate()).padStart(2,'0')}/${String(d.getUTCMonth()+1).padStart(2,'0')}/${d.getUTCFullYear()}`;} private error(status:number,code:string,message:string,data:unknown=null){return new LegacyApiException({status,code,message,data});}
}
