import { Inject, Injectable } from '@nestjs/common';
import type { Pool } from 'pg';
import { PG_POOL } from '../../../common/database/database.tokens';
import { PgErrorTranslator } from '../../../common/database/pg-error-translator';
import type { PgExecutor } from '../../../common/database/pg-executor.type';
import type { Student } from '../domain/student.entity';
import type { StudentPageQuery, StudentWriteInput } from '../domain/student.contracts';

const columns=['id','code','fullname','dob','sex','homecity','address','hair_color','email','facebook','class_id','username','description','hobbies','attachment','created_at','updated_at','deleted_at'] as const;
const aliases:Record<string,string>={id:'id',co:'code',fn:'fullname',do:'dob',sx:'sex',hc:'homecity',ad:'address',hr:'hair_color',em:'email',fb:'facebook',ci:'class_id',un:'username',de:'description',ca:'created_at',ua:'updated_at',da:'deleted_at'};
type StoredStudent=Student&{password:string};

@Injectable()
export class StudentRepository {
  constructor(@Inject(PG_POOL) private readonly pool:Pool,private readonly errors:PgErrorTranslator){}
  async findAll(columnlist?:string,executor:PgExecutor=this.pool):Promise<Student[]>{return this.run(()=>executor.query(`SELECT ${this.select(columnlist)} FROM "tra_student" WHERE "deleted_at" IS NULL ORDER BY "id" ASC`).then((r)=>r.rows as Student[]));}
  async findPage(query:StudentPageQuery,executor:PgExecutor=this.pool){return this.page(query,'"deleted_at" IS NULL','"id" ASC',executor);}
  async findDeletedPage(query:StudentPageQuery,executor:PgExecutor=this.pool){return this.page(query,'"deleted_at" IS NOT NULL','"deleted_at" DESC, "id" DESC',executor);}
  async findActiveById(id:number,executor:PgExecutor=this.pool):Promise<Student|null>{return this.run(()=>executor.query(`SELECT ${this.select()} FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NULL`,[id]).then((r)=>(r.rows[0] as Student|undefined)??null));}
  async activeHobbyMask(executor:PgExecutor=this.pool):Promise<number>{return this.run(()=>executor.query('SELECT COALESCE(bit_or("bit_value"), 0) AS mask FROM "tra_hobby" WHERE "is_active" = true').then((r)=>Number(r.rows[0]?.mask??0)));}
  async create(input:StudentWriteInput,executor:PgExecutor=this.pool):Promise<Student>{const v=input;return this.run(()=>executor.query(`INSERT INTO "tra_student" ("code","fullname","dob","sex","homecity","address","hair_color","email","facebook","class_id","username","password","description","hobbies","attachment","created_at","updated_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,NOW(),NOW()) RETURNING ${this.select()}`,[v.code!,v.fullname!,v.dob??null,v.sex??null,v.homecity||null,v.address||null,v.hair_color||null,v.email!,v.facebook||null,v.class_id||null,v.username!,v.password!,v.description||null,v.hobbies??0,v.attachment||null]).then((r)=>r.rows[0] as Student));}
  async attachmentOfActive(id:number,executor:PgExecutor=this.pool):Promise<string|null|undefined>{return this.run(()=>executor.query('SELECT "attachment" FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NULL',[id]).then((r)=>r.rows.length?(r.rows[0].attachment as string|null):undefined));}
  async updateActive(id:number,input:StudentWriteInput,executor:PgExecutor=this.pool):Promise<Student|null>{const allowed=(['fullname','dob','sex','homecity','address','hair_color','email','facebook','class_id','description','hobbies','attachment','password'] as const).filter((key)=>input[key]!==undefined);if(!allowed.length)return this.findActiveById(id,executor);const values:unknown[]=[];const set=allowed.map((key)=>{values.push(input[key]===''?null:input[key]);return `"${key}"=$${values.length}`;});values.push(id);return this.run(()=>executor.query(`UPDATE "tra_student" SET ${set.join(', ')},"updated_at"=NOW() WHERE "id"=$${values.length} AND "deleted_at" IS NULL RETURNING ${this.select()}`,values).then((r)=>(r.rows[0] as Student|undefined)??null));}
  async softDeleteActive(id:number,executor:PgExecutor=this.pool):Promise<boolean>{return this.run(async()=>{const found=await executor.query('SELECT "id" FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NULL FOR UPDATE',[id]);if(!found.rows.length)return false;await executor.query('DELETE FROM "tra_student" WHERE "id"=$1',[id]);return true;});}
  async restoreDeleted(id:number,executor:PgExecutor=this.pool):Promise<'restored'|'missing'|'conflict'>{return this.run(async()=>{const found=await executor.query('SELECT "id","code","email","username" FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NOT NULL FOR UPDATE',[id]);if(!found.rows.length)return'missing';const student=found.rows[0] as Pick<StoredStudent,'code'|'email'|'username'>;const conflict=await executor.query('SELECT 1 FROM "tra_student" WHERE "deleted_at" IS NULL AND ("code"=$1 OR "email"=$2 OR "username"=$3) LIMIT 1',[student.code,student.email,student.username]);if(conflict.rows.length)return'conflict';try{await executor.query('SAVEPOINT restore_student');const restored=await executor.query('UPDATE "tra_student" SET "deleted_at"=NULL WHERE "id"=$1 AND "deleted_at" IS NOT NULL RETURNING "id"',[id]);return restored.rows.length?'restored':'missing';}catch(error){await executor.query('ROLLBACK TO SAVEPOINT restore_student');if((error as {code?:string}).code==='23505')return'conflict';throw error;}});}
  async permanentlyDelete(id:number,executor:PgExecutor=this.pool):Promise<{attachment:string|null}|null>{return this.run(()=>executor.query('DELETE FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NOT NULL RETURNING "attachment"',[id]).then((r)=>r.rows.length?{attachment:(r.rows[0].attachment as string|null)??null}:null));}
  async countAttachmentReferences(attachment:string,executor:PgExecutor=this.pool):Promise<number>{return this.run(()=>executor.query('SELECT COUNT(*) AS count FROM "tra_student" WHERE "attachment"=$1',[attachment]).then((r)=>Number(r.rows[0]?.count??0)));}
  private async page(query:StudentPageQuery,deletedFilter:string,defaultOrder:string,executor:PgExecutor){return this.run(async()=>{const values:unknown[]=[];const conditions=[deletedFilter];if(query.search){values.push(`%${query.search}%`);const p=`$${values.length}`;conditions.push(`("fullname" ILIKE ${p} OR "description" ILIKE ${p} OR "email" ILIKE ${p})`);}if(query.excludeIds.length){values.push(query.excludeIds);conditions.push(`NOT ("id" = ANY($${values.length}::int[]))`);}const where=` WHERE ${conditions.join(' AND ')}`;const count=await executor.query(`SELECT COUNT(*) FROM "tra_student"${where}`,values);const pins=query.toplist.length?`CASE WHEN "id" = ANY($${values.length+1}::int[]) THEN 0 ELSE 1 END, `:'';const dataValues=[...values,...(query.toplist.length?[query.toplist]:[]),query.size,(query.page-1)*query.size];const data=await executor.query(`SELECT ${this.select(query.columnlist)} FROM "tra_student"${where} ORDER BY ${pins}${this.order(query.order,defaultOrder)} LIMIT $${dataValues.length-1} OFFSET $${dataValues.length}`,dataValues);const total=Number.parseInt(String(count.rows[0]?.count??0),10);return{page_info:{total_items:total,total_pages:Math.ceil(total/query.size),current:query.page,size:query.size},records:data.rows as Student[]};});}
  private select(columnlist?:string){const picked=columnlist?.split(',').map((x)=>x.trim()).filter((x):x is typeof columns[number]=>(columns as readonly string[]).includes(x));return(picked?.length?picked:columns).map((x)=>`"${x}"`).join(', ');}
  private order(order:string|undefined,defaultOrder:string){const values=order?.split('-').map((part)=>{const[alias,direction]=part.split(':');return aliases[alias]?`"${aliases[alias]}" ${direction==='1'?'DESC':'ASC'}`:null;}).filter((x):x is string=>Boolean(x));return values?.length?values.join(', '):defaultOrder;}
  private async run<T>(operation:()=>Promise<T>):Promise<T>{try{return await operation();}catch(error){throw this.errors.translate(error);}}
}
