import { Inject, Injectable } from '@nestjs/common';
import type { Pool } from 'pg';
import { PG_POOL } from '../../../common/database/database.tokens';
import type { PgExecutor } from '../../../common/database/pg-executor.type';
import type { Student } from '../domain/student.entity';
import type { StudentPageQuery } from '../http/student-request.parser';
const columns = ['id','code','fullname','dob','sex','homecity','address','hair_color','email','facebook','class_id','username','description','hobbies','attachment','created_at','updated_at','deleted_at'] as const;
const aliases: Record<string,string> = { id:'id',co:'code',fn:'fullname',do:'dob',sx:'sex',hc:'homecity',ad:'address',hr:'hair_color',em:'email',fb:'facebook',ci:'class_id',un:'username',de:'description',ca:'created_at',ua:'updated_at' };
@Injectable()
export class StudentRepository { constructor(@Inject(PG_POOL) private readonly pool: Pool) {} async findAll(columnlist?: string, executor: PgExecutor = this.pool): Promise<Student[]> { return (await executor.query(`SELECT ${this.select(columnlist)} FROM "tra_student" WHERE "deleted_at" IS NULL ORDER BY "id" ASC`)).rows as Student[]; } async findPage(query: StudentPageQuery, executor: PgExecutor = this.pool) { const values: unknown[] = []; const conditions = ['"deleted_at" IS NULL']; if (query.search) { values.push(`%${query.search}%`); const p=`$${values.length}`; conditions.push(`("fullname" ILIKE ${p} OR "description" ILIKE ${p} OR "email" ILIKE ${p})`); } if (query.excludeIds.length) { values.push(query.excludeIds); conditions.push(`NOT ("id" = ANY($${values.length}::int[]))`); } const where=` WHERE ${conditions.join(' AND ')}`; const count=await executor.query(`SELECT COUNT(*) FROM "tra_student"${where}`,values); const pins=query.toplist.length ? `CASE WHEN "id" = ANY($${values.length+1}::int[]) THEN 0 ELSE 1 END, ` : ''; const dataValues=[...values,...(query.toplist.length?[query.toplist]:[]),query.size,(query.page-1)*query.size]; const data=await executor.query(`SELECT ${this.select(query.columnlist)} FROM "tra_student"${where} ORDER BY ${pins}${this.order(query.order)} LIMIT $${dataValues.length-1} OFFSET $${dataValues.length}`,dataValues); const total=Number.parseInt(String(count.rows[0]?.count??0),10); return { page_info:{total_items:total,total_pages:Math.ceil(total/query.size),current:query.page,size:query.size},records:data.rows as Student[] }; } async findActiveById(id:number, executor:PgExecutor=this.pool):Promise<Student|null>{const result=await executor.query(`SELECT ${this.select()} FROM "tra_student" WHERE "id"=$1 AND "deleted_at" IS NULL`,[id]);return(result.rows[0] as Student|undefined)??null;} private select(columnlist?:string){const picked=columnlist?.split(',').map((x)=>x.trim()).filter((x):x is typeof columns[number]=>(columns as readonly string[]).includes(x));return(picked?.length?picked:columns).map((x)=>`"${x}"`).join(', ')} private order(order?:string){const values=order?.split('-').map((part)=>{const [alias,direction]=part.split(':');return aliases[alias]?`"${aliases[alias]}" ${direction==='1'?'DESC':'ASC'}`:null}).filter((x):x is string=>Boolean(x));return values?.length?values.join(', '):'"id" ASC'} }
