import { createContractConfig, type ContractConfig, type ContractTarget } from './contract-config';
import { requestContractTarget, type ContractHttpResponse } from './contract-http';
type Envelope<T> = { code: string; status: number; message: string; data: T };
const request = (target: ContractTarget, config: ContractConfig, path: string, method: 'DELETE' | 'GET' | 'POST' | 'PUT' = 'GET', body?: unknown) => requestContractTarget(target, path, config.timeoutMs, { method, body });
const envelope = <T>(response: ContractHttpResponse, status: number, code: string, message: string) => { expect(response.status).toBe(status); const body = response.body as Envelope<T>; expect(body).toMatchObject({ code, status, message }); expect(Object.keys(body).sort()).toEqual(['code', 'data', 'message', 'status']); return body; };
const name = (target: ContractTarget, suffix: string) => `ct-${target.name}-${suffix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`.slice(0, 45);
export function registerClassCoreContract(config: ContractConfig): void {
  describe.each(config.targets)('class core contract: %s', (target) => {
    it('keeps list, page, page/:init, and read validation contracts', async () => { const list = envelope<unknown[]>(await request(target, config, '/class'), 200, '200', 'Lấy danh sách lớp thành công'); expect(Array.isArray(list.data)).toBe(true); list.data.forEach((row) => expect(row).toEqual(expect.objectContaining({ student_count: expect.anything() }))); const page = envelope<{ page_info: unknown; records: unknown[] }>(await request(target, config, '/class/page?page=1x&size=1'), 200, '200', 'Lấy danh sách lớp theo trang thành công'); expect(page.data).toEqual(expect.objectContaining({ page_info: expect.anything(), records: expect.any(Array) })); envelope(await request(target, config, '/class/page/ignored?page=1&size=1'), 200, '200', 'Lấy danh sách lớp theo trang thành công'); envelope(await request(target, config, '/class/page?page=0&size=1'), 400, 'C601', 'Số trang không hợp lệ'); envelope(await request(target, config, '/class/page?page=1&size=0'), 400, 'C602', 'Cỡ trang không hợp lệ'); envelope(await request(target, config, '/class/bad'), 400, 'D601', 'id không hợp lệ'); envelope(await request(target, config, '/class/2147483647'), 404, 'D604', 'Không tìm thấy bản ghi lớp học'); });
    it('creates, keeps code immutable on update, and cleans exact id', async () => { const code = name(target, 'code'); let id: string | undefined; try { const created = envelope<{ id: string }>(await request(target, config, '/class', 'POST', { code: `  ${code}  `, name: '  First class  ', description: 'one' }), 200, '200', 'Tạo lớp thành công'); id = created.data.id; const detail = envelope<Record<string, unknown>>(await request(target, config, `/class/${id}`), 200, '200', 'Lấy chi tiết lớp thành công'); expect(detail.data).toMatchObject({ code, name: 'First class' }); envelope(await request(target, config, '/class', 'POST', { code, name: 'Duplicate' }), 409, 'E603', 'Mã lớp (code) đã tồn tại'); envelope(await request(target, config, `/class/${id}`, 'PUT', { code: 'ignored', name: '  not trimmed  ', description: 'two' }), 200, '200', 'Cập nhật lớp thành công'); const updated = envelope<Record<string, unknown>>(await request(target, config, `/class/${id}`), 200, '200', 'Lấy chi tiết lớp thành công'); expect(updated.data).toMatchObject({ code, name: '  not trimmed  ', description: 'two' }); envelope(await request(target, config, `/class/${id}`, 'DELETE'), 200, '200', 'Xóa lớp thành công'); id = undefined; envelope(await request(target, config, `/class/${created.data.id}`, 'DELETE'), 404, 'G604', 'Không tìm thấy bản ghi lớp học'); } finally { if (id) await request(target, config, `/class/${id}`, 'DELETE').catch(() => undefined); } });
    it('keeps mass delete partial-result shape and cleans exact ids', async () => { const codes = [name(target, 'm1'), name(target, 'm2')]; const ids: string[] = []; try { for (const code of codes) { const created = envelope<{ id: string }>(await request(target, config, '/class', 'POST', { code, name: code }), 200, '200', 'Tạo lớp thành công'); ids.push(created.data.id); } const result = envelope<{ deletedIds: string[]; blockedIds: unknown[] }>(await request(target, config, '/class/delete', 'DELETE', { ids: [...ids, 2147483647] }), 200, '200', 'Xóa các lớp thành công'); expect(result.data.deletedIds).toEqual(expect.arrayContaining(ids)); expect(result.data.blockedIds).toEqual([]); ids.length = 0; } finally { for (const id of ids) await request(target, config, `/class/${id}`, 'DELETE').catch(() => undefined); } });
  });
}
registerClassCoreContract(createContractConfig());
