import { ContractFixtures } from './contract-fixtures';
import { createContractConfig, type ContractConfig, type ContractTarget } from './contract-config';
import { requestContractTarget } from './contract-http';
type Envelope<T> = { code: string; status: number; message: string; data: T };
const request = (target: ContractTarget, config: ContractConfig, path: string, method: 'DELETE' | 'GET' | 'POST' | 'PATCH' = 'GET', body?: unknown) => requestContractTarget(target, path, config.timeoutMs, { method, body });
const envelope = <T>(response: Awaited<ReturnType<typeof request>>, message: string) => { expect(response.status).toBe(200); expect(response.body).toMatchObject({ code: '200', status: 200, message }); return response.body as Envelope<T>; };
const unique = (target: ContractTarget) => `ct-advanced-${target.name}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
export function registerClassAdvancedContract(config: ContractConfig): void {
  describe.each(config.targets)('class advanced contract: %s', (target) => {
    let fixtures: ContractFixtures; let classId: string; let studentId: string;
    beforeAll(async () => { fixtures = new ContractFixtures(); const created = envelope<{ id: string }>(await request(target, config, '/class', 'POST', { code: unique(target), name: 'Advanced' }), 'T\u1ea1o l\u1edbp th\u00e0nh c\u00f4ng'); classId = created.data.id; fixtures.trackClass(classId); studentId = await fixtures.student(`${target.name}-${classId}`); }, 15_000);
    afterAll(async () => { await fixtures.cleanup(); }, 15_000);
    it('keeps all membership reads and mutations', async () => { envelope(await request(target, config, `/class/${classId}/students?page=1&size=10`), 'L\u1ea5y danh s\u00e1ch sinh vi\u00ean trong l\u1edbp th\u00e0nh c\u00f4ng'); envelope(await request(target, config, `/class/${classId}/available-students?page=1&size=10`), 'L\u1ea5y danh s\u00e1ch sinh vi\u00ean c\u00f3 th\u1ec3 th\u00eam v\u00e0o l\u1edbp th\u00e0nh c\u00f4ng'); envelope(await request(target, config, `/class/${classId}/students`, 'POST', { studentIds: [studentId, studentId] }), 'Th\u00eam sinh vi\u00ean v\u00e0o l\u1edbp th\u00e0nh c\u00f4ng'); envelope(await request(target, config, `/class/${classId}/students/remove`, 'PATCH', { studentIds: [studentId] }), 'Lo\u1ea1i sinh vi\u00ean kh\u1ecfi l\u1edbp th\u00e0nh c\u00f4ng'); envelope(await request(target, config, `/class/${classId}/students`, 'POST', { studentIds: [studentId] }), 'Th\u00eam sinh vi\u00ean v\u00e0o l\u1edbp th\u00e0nh c\u00f4ng'); envelope(await request(target, config, `/class/${classId}/students/${studentId}`, 'DELETE'), 'Lo\u1ea1i sinh vi\u00ean kh\u1ecfi l\u1edbp th\u00e0nh c\u00f4ng'); }, 15_000);
    it('keeps copy one/mass/preview/validate/commit contracts', async () => { const one = envelope<{ id: string }>(await request(target, config, `/class/copy/${classId}`, 'POST'), 'Sao ch\u00e9p l\u1edbp th\u00e0nh c\u00f4ng'); fixtures.trackClass(one.data.id); const mass = envelope<Array<{ id: string }>>(await request(target, config, '/class/copy', 'POST', { idlist: [classId, 2147483647] }), `\u0110\u00e3 sao ch\u00e9p 1 l\u1edbp. Kh\u00f4ng t\u00ecm th\u1ea5y ids: 2147483647`); mass.data.forEach((record) => fixtures.trackClass(record.id)); const preview = envelope<{ drafts: unknown[] }>(await request(target, config, '/class/copy/preview', 'POST', { idlist: [classId] }), '\u0110\u00e3 t\u1ea1o 1 draft l\u1edbp'); const draft = (preview.data.drafts[0] as { draftKey: string; sourceId: number; values: { code: string; name: string; description?: string } }); const validation = await request(target, config, '/class/copy/validate', 'POST', { drafts: [draft] }); expect(validation.status).toBe(200); const committed = envelope<{ created: Array<{ record: { id: string } }> }>(await request(target, config, '/class/copy/commit', 'POST', { drafts: [draft] }), '\u0110\u00e3 t\u1ea1o 1 l\u1edbp'); committed.data.created.forEach((item) => fixtures.trackClass(item.record.id)); });
    it('keeps multipart import and binary export contracts', async () => { const form = new FormData(); form.append('file', new Blob([`code,name,description\n${unique(target)},Imported,desc\n`], { type: 'text/csv' }), 'classes.csv'); const imported = envelope<{ created: Array<{ id: string }> }>(await requestContractTarget(target, '/class/import', config.timeoutMs, { method: 'POST', formData: form }), 'Import th\u00e0nh c\u00f4ng 1 d\u00f2ng, l\u1ed7i 0 d\u00f2ng'); imported.data.created.forEach((record) => fixtures.trackClass(record.id)); const one = await requestContractTarget(target, `/class/export/${classId}?type=csv`, config.timeoutMs, { binary: true }); expect(one.status).toBe(200); expect(one.headers.get('content-type')).toContain('text/csv'); expect(one.headers.get('content-disposition')).toContain(`class-${classId}.csv`); expect(one.buffer.toString()).toContain('code'); const many = await requestContractTarget(target, '/class/export', config.timeoutMs, { method: 'POST', body: { idlist: [classId], type: 'json' }, binary: true }); expect(many.status).toBe(200); expect(many.headers.get('content-disposition')).toContain('classes-export.json'); expect(JSON.parse(many.buffer.toString())).toEqual(expect.any(Array)); });
  });
}
registerClassAdvancedContract(createContractConfig());
