export const CLASS_LIST_FETCH = 'CLASS_LIST_FETCH'
export const CLASS_LIST_FETCH_SUCCESS = 'CLASS_LIST_FETCH_SUCCESS'
export const CLASS_LIST_FETCH_FAIL = 'CLASS_LIST_FETCH_FAIL'

export const CLASS_DETAIL_FETCH = 'CLASS_DETAIL_FETCH'
export const CLASS_DETAIL_FETCH_SUCCESS = 'CLASS_DETAIL_FETCH_SUCCESS'
export const CLASS_DETAIL_FETCH_FAIL = 'CLASS_DETAIL_FETCH_FAIL'
export const CLASS_DETAIL_CLEAR = 'CLASS_DETAIL_CLEAR'

export const CLASS_CREATE = 'CLASS_CREATE'
export const CLASS_CREATE_SUCCESS = 'CLASS_CREATE_SUCCESS'
export const CLASS_CREATE_FAIL = 'CLASS_CREATE_FAIL'

export const CLASS_UPDATE = 'CLASS_UPDATE'
export const CLASS_UPDATE_SUCCESS = 'CLASS_UPDATE_SUCCESS'
export const CLASS_UPDATE_FAIL = 'CLASS_UPDATE_FAIL'

export const CLASS_DELETE = 'CLASS_DELETE'
export const CLASS_DELETE_SUCCESS = 'CLASS_DELETE_SUCCESS'
export const CLASS_DELETE_FAIL = 'CLASS_DELETE_FAIL'
