export const STUDENT_LIST_FETCH = 'STUDENT_LIST_FETCH'
export const STUDENT_LIST_FETCH_SUCCESS = 'STUDENT_LIST_FETCH_SUCCESS'
export const STUDENT_LIST_FETCH_FAIL = 'STUDENT_LIST_FETCH_FAIL'

export const STUDENT_DETAIL_FETCH = 'STUDENT_DETAIL_FETCH'
export const STUDENT_DETAIL_FETCH_SUCCESS = 'STUDENT_DETAIL_FETCH_SUCCESS'
export const STUDENT_DETAIL_FETCH_FAIL = 'STUDENT_DETAIL_FETCH_FAIL'
export const STUDENT_DETAIL_CLEAR = 'STUDENT_DETAIL_CLEAR'

export const STUDENT_CREATE = 'STUDENT_CREATE'
export const STUDENT_CREATE_SUCCESS = 'STUDENT_CREATE_SUCCESS'
export const STUDENT_CREATE_FAIL = 'STUDENT_CREATE_FAIL'

export const STUDENT_UPDATE = 'STUDENT_UPDATE'
export const STUDENT_UPDATE_SUCCESS = 'STUDENT_UPDATE_SUCCESS'
export const STUDENT_UPDATE_FAIL = 'STUDENT_UPDATE_FAIL'

export const STUDENT_DELETE = 'STUDENT_DELETE'
export const STUDENT_DELETE_SUCCESS = 'STUDENT_DELETE_SUCCESS'
export const STUDENT_DELETE_FAIL = 'STUDENT_DELETE_FAIL'

export const STUDENT_IMPORT = 'STUDENT_IMPORT'
export const STUDENT_IMPORT_SUCCESS = 'STUDENT_IMPORT_SUCCESS'
export const STUDENT_IMPORT_FAIL = 'STUDENT_IMPORT_FAIL'
export const STUDENT_IMPORT_CLEAR = 'STUDENT_IMPORT_CLEAR'
