import { Inject, Injectable } from '@nestjs/common';
import { CLASS_MEMBERSHIP_PERSISTENCE, CLASS_TRANSACTION, type ClassMembershipPersistencePort, type ClassTransactionPort } from '../domain/class-persistence.port';
import type { ClassPageQuery } from './class.contracts';
import { classApplicationException as classException } from './class-application.errors';

@Injectable()
export class ClassMembershipService {
  constructor(@Inject(CLASS_MEMBERSHIP_PERSISTENCE) private readonly repository: ClassMembershipPersistencePort, @Inject(CLASS_TRANSACTION) private readonly transactions: ClassTransactionPort) {}
  async getStudents(classId: number, query: ClassPageQuery) { if (!await this.repository.existsById(classId)) throw classException.membershipClassNotFound(); return this.repository.findStudentsByClass(classId, query); }
  async getAvailableStudents(classId: number, query: ClassPageQuery) { if (!await this.repository.existsById(classId)) throw classException.membershipClassNotFound(); return this.repository.findAvailableStudents(query); }
  async assign(classId: number, values: unknown[]): Promise<number[]> { const ids = this.ids(values); return this.transactions.run(async (client) => { if (!await this.repository.lockClass(classId, client)) throw classException.membershipClassNotFound(); const students = await this.repository.lockStudents(ids, client); const map = new Map(students.map((student) => [this.id(student.id), student])); const missing = ids.filter((id) => !map.has(id)); if (missing.length) throw classException.membershipStudentNotFound(missing); const deleted = ids.filter((id) => map.get(id)?.deleted_at !== null); if (deleted.length) throw classException.membershipStudentDeleted(deleted); const assigned = ids.filter((id) => map.get(id)?.class_id !== null); if (assigned.length) throw classException.membershipStudentAssigned(assigned); await this.repository.assignStudents(classId, ids, client); return ids; }); }
  async removeMany(classId: number, values: unknown[]): Promise<number[]> { const ids = this.ids(values); return this.transactions.run(async (client) => { if (!await this.repository.lockClass(classId, client)) throw classException.membershipClassNotFound(); const students = await this.repository.lockStudents(ids, client); const map = new Map(students.map((student) => [this.id(student.id), student])); const missing = ids.filter((id) => !map.has(id)); if (missing.length) throw classException.membershipStudentNotFound(missing); const deleted = ids.filter((id) => map.get(id)?.deleted_at !== null); if (deleted.length) throw classException.membershipStudentDeleted(deleted); const invalid = ids.filter((id) => this.id(map.get(id)?.class_id) !== classId); if (invalid.length) throw classException.membershipStudentNotInClass(invalid); const removed = await this.repository.removeStudents(classId, ids, client); if (removed.length !== ids.length) throw classException.membershipStudentNotInClass(); return ids; }); }
  async removeOne(classId: number, studentId: number): Promise<{ studentId: unknown }> { if (!await this.repository.existsById(classId)) throw classException.membershipClassNotFound(); const student = await this.repository.findActiveStudent(studentId); if (!student) throw classException.membershipStudentNotFound(); if (this.id(student.class_id) !== classId) throw classException.membershipStudentNotInClass(); const removed = await this.repository.removeStudent(classId, studentId); if (!removed) throw classException.membershipStudentNotInClass(); return { studentId: removed.id }; }
  private ids(values: unknown[]): number[] { const ids = [...new Set(values.map((value) => this.id(value)))]; if (!ids.length || ids.some((id) => id === null)) throw classException.invalidStudentIds(); return ids as number[]; }
  private id(value: unknown): number | null { if (typeof value === 'number') return Number.isSafeInteger(value) && value > 0 ? value : null; if (typeof value === 'string' && /^[1-9]\d*$/.test(value)) { const parsed = Number(value); return Number.isSafeInteger(parsed) ? parsed : null; } return null; }
}
